---
- name: My new module
  block:
    - name: Run the new module
      my_own_module:
        path: '{{ file_path }}'
        content: '{{ file_content }}'
      register: testout
    - name: Dump test output
      ansible.builtin.debug:
        msg: '{{ testout }}'
